apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:schreibubi/argocd.git
    targetRevision: master
    path: apps
  destination:
    name: in-cluster
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
