apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-stack
    targetRevision: 0.8.0
    helm:
      parameters:
      - name: "eck-logstash.enabled"
        value: "true"
      valuesObject:
        eck-elasticsearch:
            annotations:
                eck.k8s.elastic.co/license: basic
        eck-kibana:
            annotations:
                eck.k8s.elastic.co/license: basic
        eck-logstash:
            annotations:
                eck.k8s.elastic.co/license: basic        
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: elastic-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: kibana-ingress
  namespace: elastic-stack
spec:
  rules:
  - host: kibana.schreibubi.de
    http:
      paths:
      - backend:
          service:
            name: eck-stack-eck-kibana-kb-http
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
