apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 2.10.0
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: elastic-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
