apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-stack
    targetRevision: 0.8.0
    helm:
      parameters:
      - name: "eck-logstash.enabled"
        value: "true"
      - name: "eck-agent.enabled"
        value: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: elastic-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
