apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-stack
    targetRevision: 0.8.0
    helm:
      parameters:
      - name: "eck-logstash.enabled"
        value: "true"
      valuesObject:
        eck-elasticsearch:
            annotations:
                eck.k8s.elastic.co/license: basic
        eck-kibana:
            annotations:
                eck.k8s.elastic.co/license: basic
        eck-logstash:
            annotations:
                eck.k8s.elastic.co/license: basic        
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: elastic-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
