apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.9.0
    helm:
      valuesObject:
        controller:
          watchIngressWithoutClass: true
          updateStrategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 1
          publishService:
            enabled: false
          config:
            use-forwarded-headers: "true"
          service:
	    internal:
              ipFamilyPolicy: "PreferDualStack"
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.120.120, fdf7:aaaa:bb99::1111
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
