apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.5.3
    helm:
      valuesObject:
        helmPreUpgradeCheckerJob:
          enabled: false
	ingress:
	  enabled: true
	  host: longhorn.schreibubi.de
	  annotations:
	    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
