apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.13.12
    helm:
      valuesObject:
        speaker:
          frr:
            enabled: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
