apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.7.9
    helm:
      valuesObject:
        ingress:
          enabled: true
          host: rancher.schreibubi.de
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cattle-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
